// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihJMQJCnGqTXC15JRVlZud3Fbu5sRHao',
    appId: '1:700789236252:web:6e2c7aceccf26cf8e035d9',
    messagingSenderId: '700789236252',
    projectId: 'findom-2f489',
    authDomain: 'findom-2f489.firebaseapp.com',
    storageBucket: 'findom-2f489.appspot.com',
    measurementId: 'G-4KJCKY3EXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfqgvGp7f4KGsqtuYtFtdaARUgckC1fg',
    appId: '1:700789236252:android:d1bcbc4f5988a71be035d9',
    messagingSenderId: '700789236252',
    projectId: 'findom-2f489',
    storageBucket: 'findom-2f489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QWBsNl_7OkTcykEncLKVVbiV-dxzO0A',
    appId: '1:700789236252:ios:c0d5ef6d18bda5e1e035d9',
    messagingSenderId: '700789236252',
    projectId: 'findom-2f489',
    storageBucket: 'findom-2f489.appspot.com',
    iosBundleId: 'com.example.findom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8QWBsNl_7OkTcykEncLKVVbiV-dxzO0A',
    appId: '1:700789236252:ios:c0d5ef6d18bda5e1e035d9',
    messagingSenderId: '700789236252',
    projectId: 'findom-2f489',
    storageBucket: 'findom-2f489.appspot.com',
    iosBundleId: 'com.example.findom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihJMQJCnGqTXC15JRVlZud3Fbu5sRHao',
    appId: '1:700789236252:web:8a9a3e2013a9ea08e035d9',
    messagingSenderId: '700789236252',
    projectId: 'findom-2f489',
    authDomain: 'findom-2f489.firebaseapp.com',
    storageBucket: 'findom-2f489.appspot.com',
    measurementId: 'G-E6EDTYKNN0',
  );
}
